### ISSUE TITLE
Image caption / alt text generation module: default asset property

### ISSUE THREAD

**Issue by nezaniel** [NEOSidekick/NEOSidekick.AiAssistant#18]
Hi there,

currently for caption / alt text generation, the title asset property is preselected for writing the generated content into.
We'd like to change the default selection to caption, so there probably should be a configuration option for this.

![captionGeneration](https://github.com/user-attachments/assets/97e04b6f-138a-42a6-8a33-c85dc2d3b1c3)

**Comment by rolandschuetz** [comment]
@nezaniel You can define that it is always written to caption and the user is never asked. That can be done like this:
```yaml
NEOSidekick:
  AiAssistant:
    altTextGeneratorModule:
      propertyName: caption
```

You can find the full config options here:
https://github.com/NEOSidekick/NEOSidekick.AiAssistant/blob/main/Configuration/Settings.yaml
